### ISSUE TITLE
[Epic] Refactor generate_data.py to make it functional and simpler

### ISSUE THREAD

**Issue by shivchander** [instructlab/sdg#100]
- [ ] Num_instructions/sdg_scale_factor currently is setup only for the freeform skills - we need some logic to split that value between contexts and grounded questions for grounded skills. https://github.com/instructlab/sdg/blob/main/src/instructlab/sdg/generate_data.py#L189
- [x] The current state of this code doesn't generate grounded data - it treates them as freeform (#99, #98, #97)
- [ ] We should move the sys_prompt and system roles and delineate that to data mixing step #95 
- [ ] Let go of legacy keys used for self instruct https://github.com/instructlab/sdg/issues/102

**Comment by markmc** [comment]
I'm not sure this epic captures anything that's still actionable. If there is something actionable not captured in an individual issue, please file an issue for that. Thanks :+1:
