### ISSUE TITLE
[Epic] Support for v3 schema of knowledge taxonomy additions

### ISSUE THREAD

**Issue by russellb** [instructlab/sdg#160]
## Overview

The research team that developed InstructLab's processes has determined that we need to change how we receive and process knowledge contributions. This is necessary to get the best results we know when adding knowledge to a model.

This issue tracks the work across both the SDG repo and other repos necessary to implement this change.

> [!NOTE]
> We are not attempting to retain backward compatible for knowledge using schema versions v1 or v2. It would be more complicated and would produce lower-quality results, so the effort does not seem worthwhile.

## Tasks

- [x] instructlab-schema 0.3.0 -- https://github.com/instructlab/schema/milestone/1
  - [x] https://github.com/instructlab/schema/issues/38
  - [x] https://github.com/instructlab/schema/pull/39 
  - [x] resolve issue with publishing release to pypi (@bjhargrave looking at this)
- [x] instructlab-sdg 0.2.0 -- https://github.com/instructlab/sdg/milestone/4 (blocked on instructlab-schema 0.3.0)
  - [x] v3 schema support - https://github.com/instructlab/sdg/pull/161 
    - [x] Ensure taxonomy knowledge files that are prior to schema v3 are rejected
    - [x] Add code that knows how to convert the v3 schema into the dataset passed into the SDG pipeline
    - [x] Adapt "full" pipeline as needed for this new format
    - [x] adapt "simple" pipeline for this new format 
    - [x] Make instructlab-sdg depend on instructlab-schema>=0.3.0
  - [x] Ensure everything from this PR is covered - https://github.com/aakankshaduggal/sdg/pull/11/files
- [x] instructlab 0.18.0 -- blocked on both of the above -- https://github.com/instructlab/instructlab/milestone/16
  - [x] https://github.com/instructlab/instructlab/pull/1767
  - [x] https://github.com/instructlab/instructlab/pull/1772
  - [x] A PR that makes `ilab` depend on `instructlab-sdg>=0.2.0` (target for this epic) -- https://github.com/instructlab/instructlab/pull/1790
    - [x] Update script used in e2e test jobs to use a v3 knowledge example for testing
    - [x] Make instructlab depend on `instructlab-schema>=0.3.0`
- [x] Remove the `Switch instructlab to PR 1790` e2e hack from the `instructlab/sdg` repo -- instructlab/sdg#187

- **instructlab/taxonomy and instructlab/community repositories**

instructlab/taxonomy#1253

  - [ ] doc updates to explain the new format in any docs
  - [ ] Devise an approach for how to deal with open knowledge PRs that need to be reworked for the updated schema. The changes are not scriptable 
  - [ ] Audit docs for knowledge contribution details documentation impact

### **instructlab/schema repository**

Sample of new format: https://github.com/instructlab/taxonomy/blob/7729fcd62ca68e36225a98a954e702734cc09ae1/knowledge/science/anatomy/tonsils/qna.yaml

An updated example that is considered valid under the proposed taxonomy schema: https://github.com/russellb/taxonomy/tree/v3-example/knowledge/tonsils

Related work (non-blocking):
- [ ] We have taxonomy parsing handling in too many places. Let's use this opportunity to complete the move to instructlab-schema. 
  - [ ] https://github.com/instructlab/schema/pull/33

## **instructlab/sdg repository**

`0.2.0` milestone: https://github.com/instructlab/sdg/milestone/4

generate_data() changes, and other code it depends on
Will need work in src.instructlab.sdg.utils.taxonomy

Summary of changes implemented in this fork for preparing pipeline input: https://github.com/aakankshaduggal/sdg

> Currently we do this:
> 
> Document gets transformed to chunks
> For each chunk we attach 3 questions from the seed examples, based on a sliding window approach - so if we had more than 3 seed qa - we first attach the first 3 to the chunk, then move the window by 1 seed example and attach to the same chunk
> 
> New change:
> 
> document gets transformed to chunks
> for each chunk we simply iterate through the contexts + qa (from the seed examples) and make a call to the knowledge pipeline

Related work (non-blocking):
- [ ] Change to using taxonomy parsing code from instructlab-schema
  - [ ] https://github.com/instructlab/sdg/pull/62

### **instructlab/instructlab repo**

Related work (non-blocking): 

- [ ] Make use of instructlab-schema taxonomy parsing code

**Comment by markmc** [comment]
Closing as complete, I think instructlab/taxonomy#1253 captures the remaining known work

**Comment by markmc** [comment]
Closing
