### ISSUE TITLE
[Epic] Add data checkpointing and recovery

### ISSUE THREAD

**Issue by markmc** [instructlab/sdg#195]
In order to ensure that progress is not completely lost if there is an error during a long-run data generation process, add a checkpointing system that saves intermediate states during data generation. This allows for more granular progress tracking and recovery.

See https://github.com/aakankshaduggal/sdg/pull/19

* [x] Add capability to library -- https://github.com/instructlab/sdg/pull/222
* [x] Enable checkpointing in the CLI -- https://github.com/instructlab/instructlab/pull/1915
* [x] Enable batching in CLI (checkpointing is coupled with batching) https://github.com/instructlab/instructlab/pull/1797
* [x] File an issue to consider making use of `save_freq` in future -- https://github.com/instructlab/sdg/issues/225
